name = input("Hey Idiot What's your name?")
print(name)
q1 = input("Where are you from?")
print(q1)
q2 = input("do you know batman?")
print = ("ahhahaha " + q2 )             
q3 = input("Do you think I'm an Idiot?")
q4 = ("slap's the guy")
print = (q4)
q5 = ("Ok. I'm sorry Batman")
print = (q5)